---
editor_options: 
  markdown: 
    wrap: 72
---

# **Time table**

### 23<sup>th</sup> Jan 2024

**Venue:** 9<sup>th</sup> Floor Khon Kaen Innovation Center (KIC)
Building

-   **8:30-9:00:** Check-in
-   **9:00-10:30:** Computational thinking and study design
-   **10:30-11:00:** Coffee break & Networking
-   **11:00-12:00:** Principle of Unix
-   **12:00-13:00:** Lunch
-   **13:00-15:00:** Hands on: Experimental design and analytical
    planning
-   **15:00-15:30:** Coffee break & Networking
-   **15:30-17:30:** Hands on: Unix

### 24<sup>th</sup> Jan 2024

**Venue:** 9<sup>th</sup> Floor Khon Kaen Innovation Center (KIC)
Building

-   **8:30-9:00:** Check-in
-   **9:00-10:00:** Principle of R programming
-   **10:00-10:15:** Coffee break & Networking
-   **10:15-12:15:** Hands on: R programming
-   **12:15-13:15:** Lunch
-   **13:15-14:15:** Principle and hands on: Python
-   **14:15-14:30:** Coffee break & Networking
-   **14:30-16:30:** Principle of statistics for omics
-   **16:30-17:30:** Sample preparation

### 25<sup>th</sup> Jan 2024

**Venue:** 9<sup>th</sup> Floor Khon Kaen Innovation Center (KIC)
Building

-   **8:30-9:00:** Check-in
-   **9:00-10:00:** Graphical, visualization and interpretation
-   **10:00-10:15:** Coffee break & Networking
-   **10:15-11:45:** Principle of genomics I
-   **11:45-13:00:** Lunch
-   **13:00-14:30:** Principle of genomics II
-   **14:30-14:45:** Coffee break & Networking
-   **15:00-17:00:** Hands on: Genomics practice I
-   **16:30-17:30:** Hands on: Genomics practice II

### 26<sup>th</sup> Jan 2024

**Venue:** 9<sup>th</sup> Floor Khon Kaen Innovation Center (KIC)
Building

-   **8:30-9:00:** Check-in
-   **9:00-10:30:** Principle of transcriptomics I
-   **10:30-10:45:** Coffee break & Networking
-   **10:45-12:15:** Principle of transcriptomics II
-   **12:15-13:15:** Lunch
-   **13:15-15:15:** Hands on: Transcriptomics practice I
-   **15:15-15:30:** Coffee break & Networking
-   **15:30-17:30:** Hands on: Transcriptomics practice II

### 27<sup>th</sup> Jan 2024

**Venue:** 9<sup>th</sup> Floor Khon Kaen Innovation Center (KIC)
Building

-   **8:30-9:00:** Check-in
-   **9:00-10:30:** Principle of Metabolomics
-   **10:30-10:45:** Coffee break & Networking
-   **10:45-12:15:** Principle of Metabolomics
-   **12:15-13:15:** Lunch
-   **13:15-15:15:** Hands on: Metabolomics practice I
-   **15:15-15:30:** Coffee break & Networking
-   **15:30-17:30:** Hands on: Metabolomics practice II

### 28<sup>th</sup> Jan 2024

**Venue:** 9<sup>th</sup> Floor Khon Kaen Innovation Center (KIC)
Building

-   **8:30-9:00:** Check-in
-   **9:00-10:30:** Mini project
-   **10:30-10:45:** Coffee break & Networking
-   **10:45-12:15:** Mini project
-   **12:15-13:15:** Lunch
-   **13:15-15:15:** Mini project
-   **15:15-15:30:** Coffee break & Networking
-   **15:30-17:30:** Mini project

### 29<sup>th</sup> Jan 2024

**Venue:** 9<sup>th</sup> Floor Khon Kaen Innovation Center (KIC)
Building

-   **8:30-9:00:** Check-in
-   **9:00-10:30:** Principle of Proteomics
-   **10:30-10:45:** Coffee break & Networking
-   **10:45-12:15:** Principle of Proteomics
-   **12:15-13:15:** Lunch
-   **13:15-15:15:** Hands on: Proteomics practice I
-   **15:15-15:30:** Coffee break & Networking
-   **15:30-17:30:** Hands on: Proteomics practice II

### 30<sup>th</sup> Jan 2024

**Venue:** 9<sup>th</sup> Floor Khon Kaen Innovation Center (KIC)
Building

-   **8:30-9:00:** Check-in
-   **9:00-10:30:** Principle of CRISPR
-   **10:30-10:45:** Coffee break & Networking
-   **10:45-12:15:** Principle of CRISPR
-   **12:15-13:15:** Lunch
-   **13:15-14:45:** Hands on: CRISPR
-   **14:45-15:00:** Coffee break & Networking
-   **15:00-16:30:** Hands on: CRISPR

### 31<sup>st</sup> January 2024

**Venue:** 9<sup>th</sup> Floor Khon Kaen Innovation Center (KIC)
Building

-   **8:30-9:00:** Check-in
-   **9:00-10:30:** Microbiome
-   **10:30-10:45:** Coffee break & Networking
-   **10:45-12:15:** Microbiome
-   **12:15-13:15:** Lunch
-   **13:15-15:15:** Hands on: Microbiome
-   **15:15-15:30:** Coffee break & Networking
-   **15:30-17:30:** Hands on: Microbiome

### 1<sup>st</sup> February 2024

**Venue:** 9<sup>th</sup> Floor Khon Kaen Innovation Center (KIC)
Building

-   **8:30-9:00:** Check-in
-   **9:00-10:30:** Data integration
-   **10:30-10:45:** Coffee break & Networking
-   **10:45-12:15:** Data integration
-   **12:15-13:15:** Lunch
-   **13:15-15:15:** Hands on: Data integration I
-   **15:15-15:30:** Coffee break & Networking
-   **15:30-17:30:** Hands on: Data integration II

### 2<sup>nd</sup> February 2024

**Venue:** 9<sup>th</sup> Floor Khon Kaen Innovation Center (KIC)
Building

-   **8:30-9:00:** Check-in
-   **9:00-10:30:** Lecture Examination
-   **10:30-10:45:** Coffee break & Networking
-   **10:45-12:15:** Laboratory Examination
-   **12:15-13:15:** Lunch
-   **13:15-14:45:** Mini project (Group discussion and Presentation)
-   **14:45-15:00:** Closing ceremony
